source 'https://rubygems.org'
ruby '2.4.4'
gem 'sinatra', '>=2.0.3'
gem 'mini-heroku', '>=0.2.6'
gem 'firebase', '>=0.2.8'
gem 'certified', '>=1.0.0'
gem 'sanitize', '>=4.6.6'
gem 'firebase_id_token', '>=2.3.0'
gem 'rack-ssl', '>=1.4.1'
